### ISSUE TITLE
Writing to large log file while rotating can cause two copies to be created

### ISSUE THREAD

**Issue by rafistern** [capriza/logrotator#1]
To reproduce this:
1. Set file size to a large number e.g. 100m
2. Set interval to 1m
2. Write new lines of data to log file at a high frequency (I did every 100 milliseconds)
3. Wait for file to rotate.

You will get two copies of the rotated file created with the same timestamp but different lengths. Diff of the files will reveal that the shorter one is identical to the first half of the longer second one.

**Comment by fujifish** [comment]
Does this happen only with large files?
Can you provide code to reproduce?

**Comment by rafistern** [comment]
It seems to happen with large files because you have enough time to write to the file while it is copying.

I had:
```
    stream = fs.createWriteStream(
        fileName,
        { encoding: "utf8",
            mode: parseInt('0644', 8),
            flags: 'a' }
    );

    rotator.register(fileName, {schedule: '1m', size: '100m', compress: false, count: 10});

```
and the Python code:
        with open('../log/log.log', 'a') as the_file:
            for i in range(1,10000):
                the_file.write(''.join(random.choice(string.ascii_lowercase) for i in xrange(10 ** 5)))
                the_file.write('\n')
                time.sleep(0.01)

to test it.

**Comment by fujifish** [comment]
Replicating your test yields a different result for me. I used python to continuously write to the file (at very high speeds - I tested with 10ms interval) and rotated when reaching 100MB, the file was rotated and truncated successfully. 
I also tested with writing to the file using node WriteStream instead. This caused the file size to remain large after rotation, but the content was only the new lines. After some digging around I realised that the stream was not closed after the file truncation, so the next write it performed was at the latest position it remembered, which was after the 100MB mark. This caused the file to "grow" to a large size, even though the contents was not large.

Perhaps I'm not reproducing this correctly. Can you provide a more complete code sample (start to finish)? 
BTW, what version of node are you using?

**Comment by fujifish** [comment]
@rafistern do you want to continue checking into this?

**Comment by rafistern** [comment]
This is definitely reproducible in our application but I am having trouble creating a simple script that reproduces this and I don't really have the time so I suppose I'll let this drop. Thanks.
